import ReactDOM from 'react-dom/client';
import React from 'react';
import App from './App';
import Array from './array';
import Eventos from './eventos';
import Propriedades from './propriedades';
import Estados from './estados';
import Estados2 from './estados2';
import UseState from './useState';
import UseEffect from './useEffect';
import UseEffect2 from './useEffect2';
import UseRef from './useRef';
import UseMemo from './useMemo';
import Forms from './formularios';
import FormExe from './formsExer';
import InputComp from './input-components';
import SelectComp from './select-components';
import CheckBox from './checkbox';
import Desafio from './desafio';
import Reduce from './useReducer';

ReactDOM.createRoot(document.getElementById('root')).render(<Reduce />);
